### ISSUE TITLE
Remove zone.js and RxJS as peer dependency

### ISSUE THREAD

**Issue by DavidGangel** [J-Siu/ng2-simple-timer#1]
Dear John Sing Dao Siu,

I have an issue with your great tool.
It has dependencies for zone.js and RxJS
As a result when a new angular2 gets released and it has an upgraded version dependency of the 2 library then we have a problem.
More information:
https://github.com/angular/angular/issues/13518

Suggested solution:
https://github.com/angular/angular/issues/13518#issuecomment-267618174

**Comment by J-Siu** [comment]
I will review and properly make an update.

**Comment by J-Siu** [comment]
Since my library is using RxJS, the dependency is required. I updated the library to use the latest version.
