### ISSUE TITLE
Broken with Angular 2.4.4?

### ISSUE THREAD

**Issue by JefferE** [J-Siu/ng2-simple-timer#3]
I get this when trying to run:

ERROR in ./~/ng2-simple-timer/lib/simple-timer.js
Module not found: Error: Can't resolve 'node-uuid'

Seems this might be depending on a deprecated library?

**Comment by J-Siu** [comment]
Thank you for reporting the issue.

It took a bit longer to get it work with Angular 2.4.x. Seems there are some underlining change from 2.0.x to 2.4.x and I just can't make "uuid" or "node-uuid" to load properly with 2.4.x,  and had to switch to "angular2-uuid".

Please try the latest version 1.2.9. I also updated my Github example to use Angular 2.4.x.
