### ISSUE TITLE
Unable to load library

### ISSUE THREAD

**Issue by jayakumarsharp** [J-Siu/ng2-simple-timer#4]
I am getting below error in console but functionality is working 

 node_modules\ng2-simple-timer\lib\simple-timer.d.ts
(9,40): error TS7006: Parameter 'any' implicitly has an 'any' type.

For more info in detail..

http://stackoverflow.com/questions/41219104/angular2-ng2-simple-timer-is-not-loaded

while initialize the library getting console error.

**Comment by J-Siu** [comment]
Which version of angular2 are you using ?

**Comment by J-Siu** [comment]
For Angular2 2.2.x, must set "noImplicitAny": false in application tsconfig.json.

I updated the Readme.md with this info.
