### ISSUE TITLE
Type issue since update to 1.3.2

### ISSUE THREAD

**Issue by JDL747** [J-Siu/ng2-simple-timer#6]
Hi,

I'm getting this error since I've updated to 1.3.2 version and it's related to the subscribe function : 

`this.timer.subscribe(this.book.id, e => this.callback() );`

`TS2345: Argument of type '(e: any) => any' is not assignable to parameter of type '() => void'.`

Thanks for your help

**Comment by J-Siu** [comment]
I will check it out this weekend, this actually should not happen with 1.3.2.

**Comment by J-Siu** [comment]
Try change your line to following:

`this.timer.subscribe(this.book.id, () => this.callback() );`

Replacing the `e` with `()`.

PS: You are properly following my bad example in earlier version, sorry :( . The Readme example is now updated.

**Comment by J-Siu** [comment]
Closing for now.

**Comment by JDL747** [comment]
Thanks
