### ISSUE TITLE
Delay callback on subscription

### ISSUE THREAD

**Issue by dojo44** [J-Siu/ng2-simple-timer#7]
The current release causes the callback to be called on subscription
var o = Rx_1.Observable.timer(0, sec * 1000);

It might be nice to either change the code to this or provide some mechanism to specify the initial delay.
var o = Rx_1.Observable.timer(sec * 1000, sec * 1000);

Thanks

**Comment by J-Siu** [comment]
Updated to 1.3.5, added `delay` option for `newTimer`

`newTimer(name: string, sec: number, delay: boolan = false): boolean`

`delay`: If set to true will delay the 1st tick till the end of the first interval.
