### ISSUE TITLE
Update dependency versions to support Angular 7.0

### ISSUE THREAD

**Issue by danielmoncada** [J-Siu/ng2-simple-timer#8]
Currently, receiving the following warnings in Angular 7.0

```cs
warning " > ng2-simple-timer@6.0.0" has incorrect peer dependency "@angular/common@^6.0.0-rc.0 || ^6.0.0".
warning " > ng2-simple-timer@6.0.0" has incorrect peer dependency "@angular/core@^6.0.0-rc.0 || ^6.0.0".
```

**Comment by daanvanrobays** [comment]
The above is something I would like to request as well

**Comment by danielmoncada** [comment]
@daanvanrobays I ended up implementing this on my own, within our application. A bit easy to do, and you also have the benefit of not relying on this library.

**Comment by RZR666** [comment]
I ended up using --force when doing the npm install and it works fine.

**Comment by J-Siu** [comment]
To enable faster update, ng2-simple-timer switched to Angular CLI starting 8.2.0 and use new repository https://github.com/J-Siu/ng2-simple-timer-lib/

All version < 8.2.0 are in old repository https://github.com/J-Siu/ng2-simple-timer/
